///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace GrubHub_Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording2 recording.
    /// </summary>
    [TestModule("a43c09b5-2475-4eb1-bf8e-ef80a244698d", ModuleType.Recording, 1)]
    public partial class AdditonSteps : ITestModule
    {
        /// <summary>
        /// Holds an instance of the GrubHub_DemoRepository repository.
        /// </summary>
        public static GrubHub_DemoRepository repo = GrubHub_DemoRepository.Instance;

        static AdditonSteps instance = new AdditonSteps();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AdditonSteps()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AdditonSteps Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MSEdgeWin10RunningOracleVMVir.Qt5QWindowIcon' at .118;.681.", repo.MSEdgeWin10RunningOracleVMVir.Qt5QWindowIconInfo, new RecordItemIndex(0));
            repo.MSEdgeWin10RunningOracleVMVir.Qt5QWindowIcon.Click(".118;.681");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MSEdgeWin10RunningOracleVMVir.Qt5QWindowIcon' at .579;.778.", repo.MSEdgeWin10RunningOracleVMVir.Qt5QWindowIconInfo, new RecordItemIndex(1));
            repo.MSEdgeWin10RunningOracleVMVir.Qt5QWindowIcon.Click(".579;.778");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MSEdgeWin10RunningOracleVMVir.Qt5QWindowIcon' at .118;.682.", repo.MSEdgeWin10RunningOracleVMVir.Qt5QWindowIconInfo, new RecordItemIndex(2));
            repo.MSEdgeWin10RunningOracleVMVir.Qt5QWindowIcon.Click(".118;.682");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MSEdgeWin10RunningOracleVMVir.Qt5QWindowIcon' at .569;.869.", repo.MSEdgeWin10RunningOracleVMVir.Qt5QWindowIconInfo, new RecordItemIndex(3));
            repo.MSEdgeWin10RunningOracleVMVir.Qt5QWindowIcon.Click(".569;.869");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=687,Y=122,Width=65,Height=83}) on item 'MSEdgeWin10RunningOracleVMVir.Qt5QWindowIcon'.", repo.MSEdgeWin10RunningOracleVMVir.Qt5QWindowIconInfo, new RecordItemIndex(4));
            Validate.ContainsImage(repo.MSEdgeWin10RunningOracleVMVir.Qt5QWindowIconInfo, Qt5QWindowIcon_Screenshot1, Qt5QWindowIcon_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MSEdgeWin10RunningOracleVMVir.Qt5QWindowIcon' at .272;.375.", repo.MSEdgeWin10RunningOracleVMVir.Qt5QWindowIconInfo, new RecordItemIndex(5));
            repo.MSEdgeWin10RunningOracleVMVir.Qt5QWindowIcon.Click(".272;.375");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage Qt5QWindowIcon_Screenshot1
        { get { return repo.MSEdgeWin10RunningOracleVMVir.Qt5QWindowIconInfo.GetScreenshot1(new Rectangle(687, 122, 65, 83)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions Qt5QWindowIcon_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
