///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace GrubHub_Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GrubHub_DemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a06e447c-835e-495a-88bc-3dcd69fb2682")]
    public partial class GrubHub_DemoRepository : RepoGenBaseFolder
    {
        static GrubHub_DemoRepository instance = new GrubHub_DemoRepository();
        GrubHub_DemoRepositoryFolders.MSEdgeWin10RunningOracleVMVirAppFolder _msedgewin10runningoraclevmvir;

        /// <summary>
        /// Gets the singleton class instance representing the GrubHub_DemoRepository element repository.
        /// </summary>
        [RepositoryFolder("a06e447c-835e-495a-88bc-3dcd69fb2682")]
        public static GrubHub_DemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GrubHub_DemoRepository() 
            : base("GrubHub_DemoRepository", "/", null, 0, false, "a06e447c-835e-495a-88bc-3dcd69fb2682", ".\\RepositoryImages\\GrubHub_DemoRepositorya06e447c.rximgres")
        {
            _msedgewin10runningoraclevmvir = new GrubHub_DemoRepositoryFolders.MSEdgeWin10RunningOracleVMVirAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a06e447c-835e-495a-88bc-3dcd69fb2682")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MSEdgeWin10RunningOracleVMVir folder.
        /// </summary>
        [RepositoryFolder("68133268-50cb-47eb-be4c-31e5d033c38f")]
        public virtual GrubHub_DemoRepositoryFolders.MSEdgeWin10RunningOracleVMVirAppFolder MSEdgeWin10RunningOracleVMVir
        {
            get { return _msedgewin10runningoraclevmvir; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class GrubHub_DemoRepositoryFolders
    {
        /// <summary>
        /// The MSEdgeWin10RunningOracleVMVirAppFolder folder.
        /// </summary>
        [RepositoryFolder("68133268-50cb-47eb-be4c-31e5d033c38f")]
        public partial class MSEdgeWin10RunningOracleVMVirAppFolder : RepoGenBaseFolder
        {
            Qt5QWindowIconInfoClass _qt5qwindowiconInfo;

            /// <summary>
            /// Creates a new MSEdgeWin10RunningOracleVMVir  folder.
            /// </summary>
            public MSEdgeWin10RunningOracleVMVirAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MSEdgeWin10RunningOracleVMVir", "/form[@title>'MSEdge - Win10 [Running] -']", parentFolder, 30000, null, true, "68133268-50cb-47eb-be4c-31e5d033c38f", "")
            {
                _qt5qwindowiconInfo = new Qt5QWindowIconInfoClass(this);
            }

            /// <summary>
            /// The Qt5QWindowIconInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("f462f21c-cab1-42cb-b8ff-657183095079")]
            public class Qt5QWindowIconInfoClass : RepoItemInfo
            {
                /// <summary>
                /// Qt5QWindowIconInfoClass class constructor.
                /// </summary>
                public Qt5QWindowIconInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "Qt5QWindowIcon", "element[@instance='1']/?/?/element[@instance='0']", 60000, null, "f462f21c-cab1-42cb-b8ff-657183095079")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("e5753ad4-ec76-401f-9951-da993ce579c6")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("e5753ad4-ec76-401f-9951-da993ce579c6");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("e5753ad4-ec76-401f-9951-da993ce579c6")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("e5753ad4-ec76-401f-9951-da993ce579c6", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("68133268-50cb-47eb-be4c-31e5d033c38f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("68133268-50cb-47eb-be4c-31e5d033c38f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Qt5QWindowIcon item.
            /// </summary>
            [RepositoryItem("f462f21c-cab1-42cb-b8ff-657183095079")]
            public virtual Ranorex.Unknown Qt5QWindowIcon
            {
                get
                {
                    return _qt5qwindowiconInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Qt5QWindowIcon item info.
            /// </summary>
            [RepositoryItemInfo("f462f21c-cab1-42cb-b8ff-657183095079")]
            public virtual Qt5QWindowIconInfoClass Qt5QWindowIconInfo
            {
                get
                {
                    return _qt5qwindowiconInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
